[
    ["University of Engineering and Management Jaipur", "B.Tech Computer Science", "2020", "present"],
    ["Krishna Engineering College", "Bachelor Of Technology", "2018", "2022"],
    ["The ICT University", "Bachelor of Science in Computer Science", "2020", "present"],
    ["Board of Technical Education", "Polytechnic Diploma", "2019", "2022"],
    ["Board of Highschool and intermediate education", "Highschool", "2018", "2019"],
    ["ABV IIITM Gwalior", "B.Tech in Computer Science", "2021", "present"],
    ["Public School Darbhanga", "Higher Secondary Education", "2019", "2021"],
    ["Public School Darbhanga", "Secondary Education", "2014", "2019"],
    ["university of São Paulo", "Information System", "2017", "2020"],
    ["Chandigarh College of Engineering and Technology", "B.E. in Computer Science", "2020", "present"],
    ["university of mauritius", "Computer Science", "2018", "2021"],
    ["university of bamenda", "Nahpi", "2019", "present"],
    ["university of bamenda", "Nahpi", "2019", "present"],
    ["State Institute of engineering and Technology ", "Nilokheri", "2018", "present"],
    ["Chitkara University", "Punjab", "2021", "present"],
    ["Ahmadu Bello University", "Bachelor of Engineering", "2018", "present"],
    ["University School of Information, Communication and Technology", "Bachelor of Technology", "2021", "present"],
    ["Institute Of Technical Education and Research","Electronics and Communication and Technology", "Bachelor of Technology", "2016", "2020"]
    ["University of Bamenda", "Nahpi", "2019", "present"],
    ["University School of Information, Communication and Technology", "Bachelor of Technology", "2021", "present"],        
    ["university of bamenda", "Nahpi", "2019", "present"],
    ["University School of Information, Communication and Technology", "Bachelor of Technology", "2021", "present"],
    ["University of bamenda, Bachelor of software engineering", "COLTECH", "2021", "present"],
    ["University School of Information, Communication and Technology", "Bachelor of Technology", "2021", "present"],   
    ["University of Bamenda", "NAHPI", "2019", "present"],      
    ["Dr. BC Roy Engineering College","Bachelor of Technology","2021","present"],
    ["University of Engineering and Management", "B.Tech", "2020", "present"],
    ["University of Bamenda", "NAHPI", "2019", "present"],
    ["Groupe scolaire la manne", "Advanced level", "2015", "2020"],
    ["Kcc Institute of Technology and Management", "Bachelor of Technology", "2021", "present"],
    ["university of bamenda", "Bachelor of engineering", "2019", "present"],
    ["National Institure of Technology", "Bachelor of engineering", "2021", "present"],
    ["Government College of Engineering nagpur", "Bachelor of Technology", "2020", "present"],
    ["University School of Information, Communication and Technology", "Bachelor of Technology", "2021", "present"],
    ["vellore institute of technology","bachelor of engineering " , "2020" ,"present"],
    ["university of bamenda", "Nahpi", "2019", "present"],
    ["Indian Institute of Information Technology Allahabad", "BTech", "2021", "present"],
    ["Siantou Higher Institute of Technology", "B.Tech software Engineering", "2021", "present"],
    ["Vivekanand Education Society Institute of Technology","Bachelor of Engineering","2020","present"],
    ["University Ninth of July","Bachelor of Engineering","2017","2021"],
    ["university of Buea", "Faculty of Engineering and Technology", "2020", "present"],
    ["university of Buea", "Faculty of Engineering and Technology", "2020", "present"],
]
